### ISSUE TITLE
Dashboard bug since last updates

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#143]
Go to dashboard, hover the titles bars like FTP, SUPPORT, it reduce the title bar when mouse cursor is over it.

**Comment by rocco27** [comment]
Actually I wanted to report this today, but you were faster! :D

**Comment by Zorrototo** [comment]
Revolution theme here.

**Comment by Zorrototo** [comment]
and these too http://www.opengamepanel.org/forum/viewthread.php?thread_id=5410&rowstart=20#post_27143

**Comment by oNdsen** [comment]
this bug exists on all themes which has included the bootstrap combined. will create a pull request soon.

**Comment by own3mall** [comment]
Looked at this last night.  The problem is bootstrap conflicting with our own CSS classes.  The fix is not going to be simple.  Most likely, I will fix it by renaming our custom classes everywhere they are used.  This is why libraries like bootstrap suck.  That, or maybe I will remove bootstrap completely and convert the date/time picker to something else.

**Comment by oNdsen** [comment]
bootstrap for a date timepicker is an overkill in my opinnion.
my suggestion is to completely remove bootstrap and add this jquery plugin:
https://plugins.jquery.com/datetimepicker/

i didnt checked it right now (im on the road), but it looks very simple and i think for the use in ogp its a good solution.

**Comment by oNdsen** [comment]
take a look on this:
https://github.com/xdan/datetimepicker

**Comment by own3mall** [comment]
Should be fixed in latest.
