### ISSUE TITLE
Query failed.

### ISSUE THREAD

**Issue by Obada8** [OpenGamePanel/OGP-Website#161]
Hello,
When i make update for my panel to `ff660fcbf1ace42a7733b619c645744e90c9c719 `using original github username i got this error.
*I don't have any blacklist file.
[screenshot](https://s13.postimg.org/lgen6cc47/chrome_2017-06-16_09-45-17.png)

**Comment by own3mall** [comment]
@oNdsen Please fix this error.  Add a check for if the column does NOT exist.

**Comment by own3mall** [comment]
although the fact that it's trying to run the query again means there's something wrong with the version number or something.

**Comment by own3mall** [comment]
Still probably something you did @oNdsen lol

**Comment by oNdsen** [comment]
Ah i see, this comes when he first applied my own Repository. Give me some Minutes, will update module.php

**Comment by oNdsen** [comment]
@own3mall mmmh isnt there a SQL Query for "exists"? I didnt find some. Or how do you handle this, because on module.php are only the SQL Queries.

**Comment by oNdsen** [comment]
@Obada8 the easiest Way is to revert my own Repository on your Page by deleting just the Database Column 'display_public_ip' in the Table 'remote_servers'. After that simply Update the regular Way.
This happened on your Side because OGP has not buildt in a Check if a Column exists and there exists the Option to add other Repositories.
I need to Update the Module Updater on OGP to check in PHP if a Column exists when the Statement is "ADD", because MySQL doesnt have a "IF NOT EXISTS" Function on column Statements. So its not my fault @own3mall

**Comment by Obada8** [comment]
@oNdsen Yes you'r are right, if the column `display_public_ip `was not exist then the update work with no any error, So i will close this issue, sorry.

**Comment by own3mall** [comment]
I guess you can't in MySQL.  You can in SQL Server.  MariaDB (fork of MySQL) has one, but there's no safe way to check.  Never mind.
