### ISSUE TITLE
TS3Admin issue

### ISSUE THREAD

**Issue by rocco27** [OpenGamePanel/OGP-Website#170]
The TS3Admin page worked me fine a week maybe 2 weeks ago, but now I just found it is not possible to choose virtual server anymore. Someone else reported same issue to me.

Image: [http://imgur.com/a/Z6nfr](http://imgur.com/a/Z6nfr)

Maybe it is effected by latest "Added Display Public IP Support on TS3 Administration Module" or "Added missed Class Declaration" updates?

I also wondering why is it not possible to switch between ts3 servers on same Agent? I can create more then one ts3 servers, but TS3Admin always use the first created.

**Comment by oNdsen** [comment]
i can chose a server with my sbs theme.
can you please specify with which themes you tested it?
im only on my mobile right now, so i cannot test it in detail.

**Comment by oNdsen** [comment]
just tested it with modern and revolution theme. looks also good for me there!

**Comment by rocco27** [comment]
Hmm, okey, then wtf. I tested with Revolution-light and SimpleBootstrap.

**Comment by oNdsen** [comment]
okay, as i said im only on mobile right now.
so maybe there are some differents between regular browsers.
i will check in the next few days.

**Comment by rocco27** [comment]
I use latest Firefox.

**Comment by FarukGamer** [comment]
Try with Pale Moon ( Mozilla-derived web browser )

**Comment by rocco27** [comment]
Ok, I give a try asap.

**Comment by AlexanderCurl** [comment]
For me also working with Chrome, both mobile and Desktop, Windows and Linux.

**Comment by oNdsen** [comment]
Tested it now with SBS & Revolution:
Win10: Edge, Chrome, FF
iPhone: Chrome, Safari
On all Devices no Problem.

**Comment by own3mall** [comment]
Bring up the browser developer tools by pressing F12.  Do you see any console errors?

**Comment by rocco27** [comment]
I didn't find anything yet. I alrady tried many different devices and browsers, everywhere same issue, The TS3 server assigned to the admin acccount, site can query it, but when I choose the Agent in the TS3Admin page it is empty. I don't have any errors in the console or in the apache log.

**Comment by rocco27** [comment]
Server restarted, nothing changed.
If I stop server, then I have normal error: "TS3lib error: connection failed: 111 Connection refused".
OS: Debian 8.8
Apache: 2.4.10
PHP: 7.1

Hmm. I found another issue. Since I do test with test TS3 server and TS3Admin, the php-fpm7.1 module uses 100%(1 core) of cpu and the OGP page doesn't load anymore. I need to restart this module manually to get it back to work.

**Comment by own3mall** [comment]
Have you tried the following on the TS3 server:

1) Open your Teamspeak 3 client.
2) In your Teamspeak 3 client navigate --> Settings --> Options
3) On the left side of the new window, make sure you have "Application" selected.
4) On the right panel, you will need to check off "Advanced permissions system".
5) Choose "Apply" and then "OK" at the bottom of the window.
6) Connect to your Teamspeak 3 server.
7) Using the top navigation in your Teamspeak 3 client choose "Permissions" --> "Server Groups".
8) In the new window, make sure "Guest" is selected at the left.
9) Using the filter in the middle pane enter the following (without the quotes), "b_virtualserver_info_view".
10) Below the filter you will see the new permission option appear, you will need to right click on it and choose "Add permission".
11) Repeating steps #9 and #10 for the following two, "b_virtualserver_client_list" and "b_virtualserver_channel_list"
12) Once you completed adding the permissions for the three items above you will be set to remotely query the status of your server.

**Comment by rocco27** [comment]
"b_virtualserver_info_view", "b_virtualserver_info_view" and "b_virtualserver_channel_list" were already enabled when I registered the server.
I created more virtual servers and seems noone is working. All are orange and can not do nothing with those.

**Comment by own3mall** [comment]
Yes, it's bugged when there are multiple servers.  I haven't had a chance to dig into why either, but I experienced the same thing you mentioned rocco.  @Adjokip can you take a look if you're interested in doing so.

**Comment by Adjokip** [comment]
@own3mall - Sure, I'll take a look over things tomorrow and see if I can find the cause.

**Comment by rocco27** [comment]
Thank you guys.

**Comment by Adjokip** [comment]
The issue with the TS3Admin module seems to be related to the Smarty template system. It doesn't write any of the data to the cache files... Seems to happen [here](https://github.com/OpenGamePanel/OGP-Website/blob/1901f57dfca6100827958e77990df541d600c673/modules/TS3Admin/smarty/Smarty_Compiler.class.php#L265), I think.

I can confirm that by testing it outside of OGP - since it's based on a thirdparty system ([themasch/TS3webinterface](https://github.com/themasch/TS3webinterface) ?) the results are the same as seen from the OGP moduule. The generated template cache files are empty.

Regarding the orange status icon, it happens because Teamspeak's flood prevention kicks in. Briefly mentioned in the manual.

http://media.teamspeak.com/ts3_literature/TeamSpeak%203%20Server%20Query%20Manual.pdf

As for why the flood prevention is triggered it's because 10+ commands sent within 3 seconds... causing the IP to be blocked for 10 minutes - maybe the panel address should be whitelisted in `query_ip_whitelist.txt`.

If it isn't possible to whitelist the IP, we should maybe limit the amount of calls to the Teamspeak3 class - e.g., save the value of `$ts3_ServerInstance->getId()` to a variable rather than calling it every time in `Protocol/Teamspeak3/functions.php`

**Comment by rocco27** [comment]
Well in my case I have the server IP in the query_ip_whitelist.txt file. Panel and Agent runs on the same machine. TS3 xml already insert the server IP to the file.

**Comment by Adjokip** [comment]
#171 should fix the TS3Admin module.

But again, the orange status icon is because the Teamspeak flood system kicks in. If everything is running on the same system, make sure the address in the query whitelist file is the same as seen from the `ifconfig` command.

For example, 127.0.0.1 is in the file, but on my VM I had to add 192.168.1.199 to the file in order to prevent the flooding system kicking in.

**Comment by rocco27** [comment]
Yes, that's right. Whilelist must have the main IP of the server (internal or external) to prevent flood system from local server. So that's clear. My whitlist has those IPs:

> 127.0.0.1
> ::1
> 188.165.225.155
> 108.61.78.147
> 108.61.78.148
> 108.61.78.149
> 108.61.78.150
> 208.167.241.183
> 208.167.241.185
> 208.167.241.186
> 208.167.241.189
> 208.167.241.190

- First two generated by TS3 server if OGP doesn't touch the file (it does now, because OGP writes in the Panel IP)
-Third IP is my dedicated server IP
- All others are GameTracker IPs to able to query it

I always had this in the past (execpt ded. server IP which changed 3 times in the last 6 years).

**Comment by rocco27** [comment]
I tested your updated files. Unfortunatelly it didn't solve anything on my side.

**Comment by Adjokip** [comment]
I tested my changes again and can select virtual servers. Maybe try clearing out any files found in modules/TS3Admin/templates_c.

Others above were able to choose a virtual server, so I'm guessing that specific issue was maybe related to the PHP version.

The other issue (not being able to select other servers on the same agent, picking the first server) I didn't fix as I can't reliably test without a license. The cause is [this line](https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/TS3Admin/TS3Admin.php#L100)

**Comment by rocco27** [comment]
I was also thinking to specific PHP version problem. :/
About testing to choose more TS3 servers here is an idea. First server needs non profit licens, second doesn't need to able to run. So you can have two online at same time.

**Comment by oNdsen** [comment]
@Adjokip TS3Admin Module works before #171 without Problem on my Side.
Now i get the following Connection Error when i select the TS3 Server:
> TS3lib error: connection failed: 0 Failed to parse address "x.x.x.x"

**Comment by Adjokip** [comment]
On the server monitor for the TS3 instance, remove the user which is assigned to the server (under the Teamspeak 3 header) and reassign the user. Or assign the query port in the ogp_ts3_homes table.

The port column was added so non-standard ports may be used. In retrospect I probably should have added an extra check - feel free to add that.

**Comment by rocco27** [comment]
I have same error now.

**Comment by rocco27** [comment]
I had same error. I unassigned the admin user from ts3 vs1 and if I assign back nothing happend. :)

**Comment by own3mall** [comment]
This is fixed now thanks to @Adjokip , correct?

**Comment by rocco27** [comment]
My original issue seems to be related to php version. I will have new installation in the future, so I will do some test and give results. Until this we can close the case. Thanks to all.

**Comment by rocco27** [comment]
Anyway @Adjokip found a valid bug in TS3Admin module and fixed it.

**Comment by own3mall** [comment]
Excellent!

**Comment by rocco27** [comment]
So it was an idea maybe my issue is occur because the PHP 7.1 version.
I had before:
```
PHP 7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36 (cli) (built: Jul  7 2017 10:34:07) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.7-1+0~20170707095003.3+jessie~1.gbpd30f36, Copyright (c) 1999-2017, by Zend Technologies
```

I downgraded PHP and now I have:

> PHP 5.6.31-1+0~20170706092242.2+jessie~1.gbp94bb71 (cli)
> Copyright (c) 1997-2016 The PHP Group
> Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
>     with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

I also installed missing packages. I login by Admin account. The TS3 server assigned to Admin account. I open TS3Admin page, I can choose the Agent and after there is no any virtual server as before.

Any other ideas?

**Comment by rocco27** [comment]
So you know I downgraded the PHP from 7.1 to 5.6. TS3Admin page was empty. I just got idea to clean the 'modules/TS3Admin/templates_c' folder again and then BOOM I got back all virtual servers. This didnt't  help me with PHP 7.1, but older version got it back. I can and will test how it works with PHP 7.0, because now I see OGP is not compatible 100% with PHP 7.1. :-)

**Comment by own3mall** [comment]
Find out where it's failing in 7.1 and attach logs so we can eventually fix it.  

As far as I know, OGP works fine on 7.
