### ISSUE TITLE
SQL error when viewing arrange_ports.php page in Panel

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#313]
thread here https://www.opengamepanel.org/forum/viewthread.php?thread_id=5944
 
Error "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1" visible in page when accessing it.

In the meantime, I checked it and added missing get_lang there: https://github.com/OpenGamePanel/OGP-Website/pull/312

**Comment by Zorrototo** [comment]
I think issue may be in includes/database_mysqli.php near line 3401 at "public function getPortsRange" but I'm not sure.

Using Ubuntu 16 here with Easy Installers OGP installation and having the issue too.

**Comment by Adjokip** [comment]
https://github.com/OpenGamePanel/OGP-Website/blob/09f091a142c1318b3bd0ece564dd3670cda32774/includes/database_mysqli.php#L3405

`$home_cfg_id` is always true because of the variable assignment. So the `AND` condition is always added. `$home_cfg_id` defaults to false (hence checking it for not being false,) but because of the call to `realEscapeSingle` and using the same variable name, it'll always be true (or whatever that method returns)

```php
public function getPortsRange($ip_id,$home_cfg_id = FALSE){
	if ( !$this->link ) return false;
	
	$and_cfg_id = $home_cfg_id !== FALSE ? "AND home_cfg_id=".$this->realEscapeSingle($home_cfg_id) : "";
	[...]
}
```

fixes it.

**Comment by Zorrototo** [comment]
Thank Adjo :) https://github.com/OpenGamePanel/OGP-Website/pull/312/commits/9ab2e3425509764a96b00d6fdf82b95fd6e596ab

**Comment by own3mall** [comment]
Thanks guys.
