### ISSUE TITLE
Misleading info in footer

### ISSUE THREAD

**Issue by Zorrototo** [OpenGamePanel/OGP-Website#41]
I noticed this a long time ago but I only searched why today. The theme information in the footer is wrong, it display the Panel default theme name instead of current user theme.

Line 180 of includes/views.php:
`get_lang_f('cur_theme',@$panel_settings['theme'])`

should probably be:
`get_lang_f('cur_theme',@$_SESSION['users_theme'])`

Let me know if you think I'm right or not :P

**Comment by Adjokip** [comment]
If `$_SESSION['users_theme']` isn't set then there won't be any theme info at the bottom.

I'd suggest:
~~~
 get_lang_f('cur_theme', !empty($_SESSION['users_theme']) ? $_SESSION['users_theme'] : @$panel_settings['theme'])
~~~

We can drop the error suppression on the $_SESSION variable thanks to the empty check. Can't drop it on the second part / `panel_settings`, because the panel doesn't initialize all the settings upon installation. 

It's something I noticed too. I was going to eventually submit a pull request with some other small fixes.
