### ISSUE TITLE
Adding commandline manager Arma 3

### ISSUE THREAD

**Issue by includes08** [OpenGamePanel/OGP-Website#425]
Is there a way to add the following; see video for more info

https://youtu.be/hgoQiYBgJO0?t=258

at the 4:18 mark it shows a command line editor, am i overlooking something or is this something they made on their own? As of now i have a lot of trouble running mods on arma `-mod=@test;@test2` won't work neither will `-servermod=@test1;test2` it will just load the first mod present. The only way of running mods is by seperating them 

example;
`-mod=@test -mod=@test2 `
i've also tried;
`-mod=@test\;@test2\
`
is there a way we can make this easier something more automated like the video? Also some of the mods don't really work, it breaks the server with no error. Or the mod just doesn't launch either. On arma its not my first rodeo setting up a server with linux.

**Comment by Zorrototo** [comment]
This is a video of something else than OGP.

Please open a support thread on our OGP forum if you need support but I'm closing this non issue, unrelated to OGP (the video shows another Panel and you do not provide any info about OGP I'm not even sure you use OGP).

If command line additional parameter you set in OGP don't work it is probably because of the special character used to separate the mods (but whee do you put that?), but let use the forum if you have an issue with OGP and follow the rules to provide all the necessary information to be able to understand and help you.
