### ISSUE TITLE
Api BUG or What?

### ISSUE THREAD

**Issue by vegtelenmt2** [OpenGamePanel/OGP-Website#471]
The problem is that you only create a server based on an admin token. However, this is not entirely good, because something has happened now and so it packs the tenants' servers into the admin folder.

Since I have my own custom website, api requires the admin token to create the server. So unfortunately it puts the servers in the admin folder.

I don't use whmcs. 
My own unique website.

**Comment by Zorrototo** [comment]
When I suggested you to open an issue on GitHub on the WHMCS mod that I supposed you were using, it was because I supposed there was an issue with WHMCS mod, BUT you then said that it was your own website/shop so the issue is how you made your website, from the info in the thread https://www.opengamepanel.org/forum/viewthread.php?thread_id=7286 you said you were using the Admin account token to create servers (so the Admin user, right?), and also that you had a custom installation path with the username in the path.
So if I understand how everything is setup on your side it is normal that it creates the game server under the Admin account folder because:
- you setup custom path with username
- you install servers with the Admin account token

So if there is an issue it is on how you made your website. You should have it use the User token if you want the installation to create a path with the User name.

Maybe I didn't understand everything but it is up to you to give all necessary info at some point if you want others to understand you.

**Comment by vegtelenmt2** [comment]
The problem is that you don't create the service with a user token, so you have to have an admin token in it, because that's the only way it works. You do not create the service with a plain user token.

**Comment by Zorrototo** [comment]
Let continue on the forum for now, and let see.
