### ISSUE TITLE
SQUAD 64 win- update required

### ISSUE THREAD

**Issue by ancientevil** [OpenGamePanel/OGP-Website#621]
https://github.com/OpenGamePanel/OGP-Website/blob/master/modules/config_games/server_configs/squad_win64.xml

Squad has updated and we cant get server to work with multihomesetting at startupline. 
If i start squad with a bat file without that setting everything works.

Squad developer also switched from steam to epic connections EOS, cant see anything else that´s not working.

DESCRIPTION:
Startupline with -Multihome not working. I need to remove this setting to get game to work
Is it possible to remove setting -MULTIHOME=X.X.X.X or make it "optional" for the servers startupline?

**Comment by Zorrototo** [comment]
Isn't this setting required to set the IP you want to use for the game server? Is there official statement about the issue?

**Comment by ancientevil** [comment]
Ok i´ll write official statements first

-beaconport= is the flag you need to have set in your commandline. You may place this anywhere, but recommend being towards the end of the commandline next to -log - without the flag, it will default to having a "silent" -beaconport=15000, and it is a UDP listen port. If you only have one server, this will be fine. If you have more than one server, you will need to give each a unique beacon port. Recommend 5 port spaces to be safe ie. Server1 has -beaconport=15000, Server2 has -beaconport=15005, etc etc


Still my problem is when using multihome=public ip or multihome= private ip it will not work
Server will only work if i disable -multihome therefor i suggest an option to be able to disable this in OGP when configuring server

**Comment by Zorrototo** [comment]
No, I'm saying is there any official statement (link to it?) explaining why we should not use a [widely known UE parameter](https://forums.unrealengine.com/t/how-to-set-the-network-adapter-for-server-multiplayer/480731) for setting the IP that is binding to the game server on start. I'm not talking about how to run multiple servers on the same IP. As far as I know the "multihome" parameter is used for a lot of game servers and I'm surprised you're asking to remove it as it would remove the ability to decide the IP the game server is run on. also, more details on the errors would be appreciated (logs? description of issue?).

Maybe we should remove the parameter, maybe the issue is on your side.

**Comment by Zorrototo** [comment]
No, I'm saying is there any official statement (link to it?) explaining why we should not use a [widely known UE parameter](https://docs.unrealengine.com/4.27/en-US/ProductionPipelines/CommandLineArguments/) for setting the IP that is binding to the game server on start. I'm not talking about how to run multiple servers on the same IP. As far as I know the "multihome" parameter is used for a lot of game servers and I'm surprised you're asking to remove it as it would remove the ability to decide the IP the game server is run on. also, more details on the errors would be appreciated (logs? description of issue?).

Maybe we should remove the parameter, maybe the issue is on your side.

**Comment by ancientevil** [comment]
Yeha you are right multihome is a problem my side.

But the other statements is correct. -beaconport (default is 15000)

**Comment by Zorrototo** [comment]
If there is an issue globally with how it is now, let's fix it, but without more information I see it just as someone who want to modify something in OGP for their convenience and it may affect others negatively without proper reason. Provide more information if this is the case.

**Comment by ancientevil** [comment]
Sure i will but still -beaconport needs to be added as a input parameter. It works if you put it in commandline manually but this is stated officially

**Comment by Zorrototo** [comment]
Beacon port should be added as an automatic parameter then, calculated from the port set in Panel (like other games servers like Killing Floor where multiple ports are set depending on the game port).

**Comment by Zorrototo** [comment]
Now that I think about it, I hosted a bunch of Squad servers and there was never an issue about this beaconport parameter not being set, and the Squad server wiki doesn't even list the beacon port as being needed to be opened in the firewall. Again, do you have a link to some official statement explaining the need for this parameter? What happens if you do not set it?

**Comment by ancientevil** [comment]
No it´s because as i wrote before OWI has implemented epic online services instead of steam. I dont they have had time to update their wiki yet. But still -beaconport is a must

**Comment by Zorrototo** [comment]
At some point if you cannot reply to my request I can't and will not help more.

**Comment by ancientevil** [comment]
The official statement is behind a "locked" discord for hosting partners. And as i said I think they haven´t had time to update their wiki yet.

**About EOS integration is found here:**
https://joinsquad.com/2023/12/12/squad-7-0-live-release-notes/
"System & Gameplay Updates
Integrated Epic Online Services"

**From discord that is only for "approved partners "**

You need to have ICMPv4 open in your firewall (This is a "ping") for latency to report correctly in the server browser. The test for this is to try to ping the IP for your server.

You need to be punching through NAT. If you don't it won't work due to the above. Particularly a thing for home-hosters.

-beaconport= is the flag you need to have set in your commandline. You may place this anywhere, but recommend being towards the end of the commandline next to -log - without the flag, it will default to having a "silent" -beaconport=15000, and it is a UDP listen port.

 If you only have one server, this will be fine. If you have more than one server, you will need to give each a unique beacon port. 

Recommend 5 port spaces to be safe ie. Server1 has -beaconport=15000, Server2 has -beaconport=15005, etc etc
The -beaconport= flag is mobile - you can change your beaconport to wherever you wish, though it would be recommended to stay in the 15000-15050 range as that's what has been tested.
Your Game Port (commandline argument PORT=) whichever it is, must be exposed and contactable. You cannot have this locked down, and a firewall rule must be in place to allow traffic to pass.
You must have DNS throughput to the box. Otherwise it can't resolve EOS things.
You must allow the beacon port through the firewall - your server may show up, but it will not be joinable unless you do.


Still we have problems hosting this behind NAT- to sad they integrated this EOS instead of steamservices that worked flawless

Is this enough information? @Zorrototo

**Comment by Zorrototo** [comment]
So the information about the server is locked behind private Discord? What a great dev team..

What about the testing I asked for.

**Comment by ancientevil** [comment]
If i don´t set any -beaconport in startup-parameter, log says:
_Created socket for bind address: 192.168.2.2 on port 15000_ anyways.

Still we have problems of testing server properly because we are behind NAT on our server and we cant figure how to configure NAT punchtrhrough and DMZ is not actual on this server and server needs publicIP adress binded to gameserver.

**Comment by ancientevil** [comment]
If i add public ip to serverthen  i get the winsockerror on port 15000. 
But that is because we are behind NAT.

I hope i explained as good as i can for now :=)

**Comment by own3mall** [comment]
Please use forums to figure this out further.
