### ISSUE TITLE
Verify Steam AppId for XML Game Server Configs

### ISSUE THREAD

**Issue by own3mall** [OpenGamePanel/OGP-Website#66]
Can someone please compare this list (https://developer.valvesoftware.com/wiki/Dedicated_Servers_List) to our XML config files and update the installer_name AppIds where needed?  I noticed a lot are out of date or incorrect.  I could do this myself if no one else will, but it would be nice if someone else did it.

**Comment by Adjokip** [comment]
I made a quick script to loop over the files and check the appids, comparing them with the SteamApps/GetAppList Steam API method. Seems there's a few that need changed.

Script is here: https://gist.github.com/Adjokip/52b571dd036011f43f8e7ab0370a4656
Output: https://gist.github.com/Adjokip/e883678000f0d37c984ba4566f132412

It seems only Space Engineers and Starbound needs changed. It doesn't seem like Mount and Blade: Warband is installed from SteamCMD. Because much like the previously mentioned games, it also uses the game ID in the config files... but I don't see a dedicated server appId for it.

**Comment by Zorrototo** [comment]
ho quicker than me :D
